name: Build LaTeX PDFs

on:
  push:         # Trigger the workflow on each push to the repository
    branches:
      - main    # Specify the branch (e.g., 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest

    # Use the pre-built LaTeX Docker image from texlive
    container:
      image: texlive/texlive:latest  # Use the official texlive Docker image

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Compile the LaTeX file for Template A
      - name: Compile Template A to PDF
        run: |
          pdflatex -interaction=nonstopmode example_templateA.tex
          pdflatex -interaction=nonstopmode example_templateA.tex  # Run twice for cross-references

      # Step 3: Compile the LaTeX file for Template B
      - name: Compile Template B to PDF
        run: |
          pdflatex -interaction=nonstopmode example_templateB.tex
          pdflatex -interaction=nonstopmode example_templateB.tex  # Run twice for cross-references

      # Step 4: Mark the repository as safe for Git (required for GitHub Actions)
      - name: Mark directory as safe for Git
        run: git config --global --add safe.directory /__w/NILU-Beamer-Template/NILU-Beamer-Template

      # Step 5: Stash uncommitted changes (PDFs)
      - name: Stash uncommitted changes
        run: git stash --include-untracked

      # Step 6: Fetch the latest changes and rebase
      - name: Fetch and Rebase
        run: |
          git fetch origin
          git pull --rebase origin main

      # Step 7: Pop the stashed changes (restore the PDFs)
      - name: Pop stashed changes
        run: git stash pop

      # Step 8: Commit and push the PDFs back to the repository
      - name: Commit and Push PDFs
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add example_templateA.pdf example_templateB.pdf
          git commit -m "Update PDFs on commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
