name: Package NILU Beamer Theme

# Trigger the workflow on every push to the main branch or on tag creation
on:
  push:
    branches:
      - main
  # You can also trigger this workflow on tag creation
  # or manually through the GitHub Actions UI.
  tags:
    - '*'

jobs:
  create-zip:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create the zip file containing the necessary files
      - name: Create zip of theme files
        run: |
          mkdir package
          cp beamerthemenilu.sty package/                # Copy .sty file
          cp LICENSE package/                            # Copy LICENSE
          cp -r graphics package/                        # Copy graphics directory
          cd package                                     # Move into the package directory
          zip -r ../NILU-Beamer-Theme.zip *              # Create zip of package contents

      # Step 3: Upload the custom zip file as a GitHub release asset
      - name: Upload Zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # GitHub token to authorize the release
        with:
          upload_url: ${{ github.event.release.upload_url }}  # Automatically gets the release URL
          asset_path: ./NILU-Beamer-Theme.zip                # Path to the zip file
          asset_name: NILU-Beamer-Theme.zip                  # Name of the uploaded zip file
          asset_content_type: application/zip                # Set the content type

